name: GitLab CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs on: ubuntu-latest
    steps:
      -name: checkout
      -uses: actions/checkout@v2
      -name: build
      -run: npm install
      -run: npm run build
      -name: run
      -run: npm start
